### ISSUE TITLE
Module pyrabbit2

### ISSUE THREAD

**Issue by lunauser** [trendmicro/defplorex#1]
Hi!

Try this module https://github.com/deslum/pyrabbit2. This is fork pyrabbit with new features and support

**Comment by vinayakumarr** [comment]
How to install defplorex. Is there any tutorials

**Comment by phretor** [comment]
Thanks @lunauser for the suggestion: let us know if pyrabbit2 works better than what we recommend for DefPloreX, and we'll be happy to include it.

@vinayakumarr, quoting the [README](https://github.com/trendmicro/defplorex/blob/master/README.md):

> [...] we're releasing an example use of the DefPloreX approach to distributed data processing using Elasticsearch (ES). This is *not meant to be a ready-to-use, plug-n-play solution*, but rather *a framework that you can reuse*, extend and improve to adapt it to your needs.

In other words, we're releasing the foundations of DefPloreX, not the entire code base.

**Comment by ccding** [comment]
It is spam. Opening identical issues in 28 repos to advertise your project is definitely a spam.
